"""fixing the column created_at

Revision ID: 8912cc7887c8
Revises: a9fbc008b5a3
Create Date: 2024-08-14 10:05:54.345674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8912cc7887c8'
down_revision: Union[str, None] = 'a9fbc008b5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
